### ISSUE TITLE
"High Level Design" typos

### ISSUE THREAD

**Issue by Thuney** [RobotCasserole1736/RoboSim#6]
-perripherial +peripheral

-capiability + capability

**Comment by cyberatlas** [comment]
we'll look at it at lunch tomorrow, bed time

**Comment by Thuney** [comment]
Was actually just to let Chris know he had typos in his documentation, nothing else.

**Comment by gerth2** [comment]
Nah that's awesome, thanks guys! I know there's some,out of date info there
(like, we're using an arduino mega, not an uno). I'll try and update it
this week.

**Comment by gerth2** [comment]
Do you guys have edit abilities on here? I should add you if not. Feel free to update as you see fit.

**Comment by Thuney** [comment]
I don't think I have edit capabilities. It just gave me the option to fork
the repo. I'm going to start looking at the code to see what I can do to
help.
